name: Glitch Sync

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Glitch Project
      uses: TheTorpian/Lee-Mod-Bot@master
      with:
        project-id: '${{ secrets.projectId }}'
        auth-token: '${{ secrets.authToken }}'
